//USER MOVIE
export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";

//GROUP CINEMA
export const GET_LIST_GROUP_CINEMA = "GET_LIST_GROUP_CINEMA";
export const SET_CHOSEN_GROUP_CINEMA = "SET_CHOSEN_GROUP_CINEMA";
export const GET_CINEMA_MOVIES = "GET_CINEMA_MOVIES";
export const GET_SHOWTIME_INFO = "GET_SHOWTIME_INFO";
export const GET_GROUP_CINEMA_INFO = "GET_GROUP_CINEMA_INFO";

//LOGIN
export const LOGIN = "LOGIN";
export const LOGIN_ADMIN = "LOGIN_ADMIN";

//SIGN-UP
export const SIGN_UP = "SIGN_UP";

//ACCOUNT
export const GET_LIST_ACCOUNT = "GET_LIST_ACCOUNT";
export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

//ADMIN MOVIE
export const ADD_MOVIE = "ADD_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const UPLOAD_MOVIE_IMG = "UPLOAD_MOVIE_IMG";
export const LOG_OUT ='LOG_OUT'
